language: cpp
compiler: gcc
dist: trusty
sudo: require
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - chmod +x travis_build.sh
install:
  - sudo apt-get install cmake
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install zlib1g-dev
script:
  - ./travis_build.sh
  - pwd
  - ./libgramtools/submods/tests/test_main
notifications:
  email: false
