language: cpp
compiler: gcc
dist: trusty
sudo: require

# Need gcc >= 5 to support c++17
# Need gcc >= 7 to support c++17 std::optional
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - chmod +x travis_build.sh
  - eval "${MATRIX_EVAL}"


install:
  - sudo apt-get install cmake
  #- sudo apt-get install -qq g++-6
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install zlib1g-dev
script:
  - ./travis_build.sh
  - pwd
  - ./libgramtools/submods/tests/test_main
notifications:
  email: false
